// --- Quest atlas --------------------------------------------------------------
// The "Atlas de quests" map layer: pick a quest and the map plots the tiles where
// it actually happens — teleport destinations, doors, levers, boss rooms — on the
// right floors, with the server's own mission texts alongside.
//
// Data comes from `public/quests.json`, generated by `node tools/gen-quests.mjs`
// off the OT's quest catalog + quest scripts. Regenerate after updating the OT.
import { useQuery } from '@tanstack/react-query'

/** One tile the quest touches. */
export type QuestPoint = {
  x: number
  y: number
  z: number
  /** Derived from the script file name ("Enter Omruc Room"). */
  label: string
  kind: 'action' | 'movement' | 'npc' | 'creature' | 'other'
  /**
   * Mission number this tile belongs to, or null when the script serves several
   * missions at once (the tombs share one teleport script) — the generator
   * refuses to guess rather than attributing it to the wrong step.
   */
  mission: number | null
}

/** A questlog step, with the state text the server shows as you progress. */
export type QuestMission = { n: number; name: string; texts: string[] }

export type Quest = {
  id: string
  name: string
  /** Empty for quests that are fully scripted but never registered in the questlog. */
  missions: QuestMission[]
  points: QuestPoint[]
  /** Total points before the display cap, or 0 when nothing was dropped. */
  truncated: number
  floors: number[]
  x: number
  y: number
  z: number
  bounds: { x1: number; y1: number; x2: number; y2: number } | null
}

export type QuestsFile = { generated: string; quests: Quest[] }

/**
 * Static data baked at build time. Fetched only once the layer is switched on —
 * the atlas is by far the heaviest of the map's assets (~300 KB), and most
 * sessions never open it.
 */
export function useQuests(enabled: boolean) {
  return useQuery({
    queryKey: ['quests'],
    enabled,
    staleTime: Infinity,
    gcTime: Infinity,
    queryFn: async (): Promise<QuestsFile> => {
      const res = await fetch('/quests.json')
      if (!res.ok) throw new Error('quests')
      return res.json()
    },
  })
}

/** Quests whose name matches a search term, alphabetically. */
export function searchQuests(quests: Quest[], term: string): Quest[] {
  const q = term.trim().toLowerCase()
  if (!q) return quests
  return quests.filter((x) => x.name.toLowerCase().includes(q))
}

/**
 * Points of one mission, or the unattributed ones when `mission` is null. Used to
 * light up just the step you are reading.
 */
export function missionPoints(quest: Quest, mission: number | null): QuestPoint[] {
  return quest.points.filter((p) => p.mission === mission)
}

/** Missions that actually have tiles on the map, so dead steps aren't offered. */
export function mappedMissions(quest: Quest): QuestMission[] {
  const have = new Set(quest.points.map((p) => p.mission).filter((m): m is number => m !== null))
  return quest.missions.filter((m) => have.has(m.n))
}
