// --- Raids / invasions --------------------------------------------------------
// The "Invasiones" map layer. Every raid the server can fire, with the exact
// tiles it spawns on, the creatures it pours in, and the literal broadcast the
// world reads out when it starts.
//
// Data comes from `public/raids.json`, generated by `node tools/gen-raids.mjs`
// off the OT server's own `raids/*.xml`. Regenerate after updating the OT tree.
import { useQuery } from '@tanstack/react-query'

/** A creature dropped on one exact tile (bosses, and 1x1 "areas"). */
export type RaidSpawn = {
  name: string
  x: number
  y: number
  z: number
  /** ms after the raid starts */
  delay: number
  /** >1 only for stacked single-tile spawns */
  amount?: number
}

/** A rectangle the raid floods with monsters. */
export type RaidArea = {
  x1: number
  y1: number
  x2: number
  y2: number
  z: number
  delay: number
  monsters: { name: string; amount: number }[]
}

export type Raid = {
  /** `region/file`, stable across regenerations — used as the React key. */
  id: string
  name: string
  /** Internal code from raids.xml ("GoEdron"), null when unscheduled. */
  code: string | null
  region: string
  regionKey: string
  /** On the server's raid timer? Unscheduled ones are real but never roll. */
  scheduled: boolean
  /** Minutes between rolls (raids.xml `interval2`). */
  interval: number | null
  /** Relative weight when raids compete for a slot (raids.xml `margin`). */
  margin: number | null
  /** Pin position: the boss tile, else the centre of the invaded ground. */
  x: number
  y: number
  z: number
  bounds: { x1: number; y1: number; x2: number; y2: number }
  floors: number[]
  /** Distinct named creatures spawned on their own tile. */
  bosses: string[]
  /** Total creatures the raid spawns. */
  creatures: number
  announcements: { delay: number; message: string }[]
  spawns: RaidSpawn[]
  areas: RaidArea[]
}

export type RaidsFile = { generated: string; raids: Raid[] }

/**
 * Two of the seventeen raid regions are not city names, so they need translating;
 * the rest read identically in both site languages and are served as-is.
 */
const REGION_ES: Record<string, string> = {
  chayenne: 'Reino de Chayenne',
  fury_gate: 'Puertas de Furia',
}

export function raidRegion(raid: Raid, lang: string): string {
  return lang.startsWith('es') ? (REGION_ES[raid.regionKey] ?? raid.region) : raid.region
}

/** Raids are static data baked at build time — fetch once, keep forever. */
export function useRaids() {
  return useQuery({
    queryKey: ['raids'],
    staleTime: Infinity,
    gcTime: Infinity,
    queryFn: async (): Promise<RaidsFile> => {
      const res = await fetch('/raids.json')
      if (!res.ok) throw new Error('raids')
      return res.json()
    },
  })
}

/**
 * Every creature the raid spawns with its total count, biggest first. Areas and
 * single tiles are merged because a player only cares what shows up, not which
 * XML element produced it.
 */
export function raidRoster(raid: Raid): { name: string; amount: number }[] {
  const totals = new Map<string, number>()
  const add = (name: string, n: number) => totals.set(name, (totals.get(name) ?? 0) + n)
  for (const s of raid.spawns) add(s.name, s.amount ?? 1)
  for (const a of raid.areas) for (const m of a.monsters) add(m.name, m.amount)
  return [...totals]
    .map(([name, amount]) => ({ name, amount }))
    .sort((p, q) => q.amount - p.amount || p.name.localeCompare(q.name))
}

/**
 * How the raid unfolds: announcements and spawn waves on one timeline, ordered
 * by the delay each carries in the XML.
 */
export type RaidStep =
  | { at: number; kind: 'announce'; message: string }
  | { at: number; kind: 'spawn'; label: string; count: number }

export function raidTimeline(raid: Raid): RaidStep[] {
  const steps: RaidStep[] = raid.announcements.map((a) => ({
    at: a.delay,
    kind: 'announce' as const,
    message: a.message,
  }))

  // Waves that fire at the same moment are one beat for the reader.
  const waves = new Map<number, Map<string, number>>()
  const push = (at: number, name: string, n: number) => {
    const w = waves.get(at) ?? new Map<string, number>()
    w.set(name, (w.get(name) ?? 0) + n)
    waves.set(at, w)
  }
  for (const s of raid.spawns) push(s.delay, s.name, s.amount ?? 1)
  for (const a of raid.areas) for (const m of a.monsters) push(a.delay, m.name, m.amount)

  for (const [at, w] of waves) {
    const parts = [...w]
      .sort((p, q) => q[1] - p[1])
      .map(([name, n]) => (n > 1 ? `${n}× ${name}` : name))
    steps.push({
      at,
      kind: 'spawn',
      label: parts.join(', '),
      count: [...w.values()].reduce((n, k) => n + k, 0),
    })
  }

  return steps.sort((p, q) => p.at - q.at || (p.kind === 'announce' ? -1 : 1))
}

/** "0s" / "1m 30s" — raid delays are short, so seconds stay visible. */
export function raidDelay(ms: number): string {
  const s = Math.round(ms / 1000)
  if (s < 60) return `${s}s`
  const m = Math.floor(s / 60)
  const rest = s % 60
  return rest ? `${m}m ${rest}s` : `${m}m`
}

/**
 * The raid roll interval, in hours or days. `interval2` is in minutes and the
 * real values are coarse (500 min ≈ 8 h, 1440 min = 1 day), so a rounded human
 * figure is honest and far more readable than "500 min".
 */
export function raidInterval(minutes: number | null, lang: string): string | null {
  if (!minutes) return null
  const es = lang.startsWith('es')
  if (minutes >= 1440) {
    const d = Math.round(minutes / 1440)
    return es ? (d === 1 ? '~1 día' : `~${d} días`) : d === 1 ? '~1 day' : `~${d} days`
  }
  const h = Math.round(minutes / 60)
  return es ? (h === 1 ? '~1 hora' : `~${h} horas`) : h === 1 ? '~1 hour' : `~${h} hours`
}
