// --- Travel network -----------------------------------------------------------
// The "Red de viajes" map layer: every NPC that sells passage — boats, magic
// carpets, ice sleds, the Kazordoon steamboat — with the real drop-off tile and
// the real price in gold, read straight from the server's NPC scripts.
//
// Data comes from `public/travel.json`, generated by `node tools/gen-travel.mjs`.
// Regenerate after updating the OT tree.
import { useQuery } from '@tanstack/react-query'

export type TravelRoute = {
  /** Destination label (the keyword the NPC answers to). */
  to: string
  /** Drop-off tile. */
  x: number
  y: number
  z: number
  /** Fare in gold. 0 = free ride. */
  cost: number
}

export type TravelNpc = {
  name: string
  /** 'boat' for tagged sailors, 'other' for carpets, sleds, minecarts… */
  kind: 'boat' | 'other'
  /** Every tile this NPC stands on (ferrymen work more than one quay). */
  at: { x: number; y: number; z: number }[]
  routes: TravelRoute[]
  /** Id of the place its first dock belongs to. */
  place: number
}

/** A quay/hub: docks and drop-off tiles close enough to walk between. */
export type TravelPlace = { id: number; name: string; x: number; y: number; z: number }

/** One paid ride between two places. */
export type TravelEdge = { from: number; to: number; npc: string; cost: number }

export type TravelFile = {
  generated: string
  npcs: TravelNpc[]
  places: TravelPlace[]
  edges: TravelEdge[]
}

/** Static data baked at build time — fetch once, keep forever. */
export function useTravel() {
  return useQuery({
    queryKey: ['travel'],
    staleTime: Infinity,
    gcTime: Infinity,
    queryFn: async (): Promise<TravelFile> => {
      const res = await fetch('/travel.json')
      if (!res.ok) throw new Error('travel')
      return res.json()
    },
  })
}

export type Fare = { total: number; legs: TravelEdge[] }

/**
 * Cheapest chain of paid rides between two places, transfers included — the
 * answer to "what does it actually cost to get from Thais to Svargrond?" (160 gp
 * via Kazordoon, not the 180 the direct ship charges).
 *
 * This is a FARE model, not a pathfinder: it assumes you can walk from the quay
 * you land on to the next captain, which is how the places were clustered in the
 * first place. Walking distance and obstacles are "Cómo llegar"'s job.
 */
export function cheapestFare(data: TravelFile, from: number, to: number): Fare | null {
  if (from === to) return { total: 0, legs: [] }

  const adj = new Map<number, TravelEdge[]>()
  for (const e of data.edges) {
    const list = adj.get(e.from)
    if (list) list.push(e)
    else adj.set(e.from, [e])
  }

  // The graph is tiny (tens of nodes), so a plain scan beats a heap and keeps the
  // code readable.
  const dist = new Map<number, number>([[from, 0]])
  const prev = new Map<number, TravelEdge>()
  const done = new Set<number>()

  for (;;) {
    let at = -1
    let best = Infinity
    for (const [node, d] of dist) {
      if (!done.has(node) && d < best) {
        best = d
        at = node
      }
    }
    if (at === -1) break
    if (at === to) break
    done.add(at)

    for (const e of adj.get(at) ?? []) {
      const next = best + e.cost
      if (next < (dist.get(e.to) ?? Infinity)) {
        dist.set(e.to, next)
        prev.set(e.to, e)
      }
    }
  }

  const total = dist.get(to)
  if (total === undefined) return null

  const legs: TravelEdge[] = []
  let cur = to
  // Guarded against a malformed graph rather than trusting the chain blindly.
  while (cur !== from && legs.length <= data.edges.length) {
    const e = prev.get(cur)
    if (!e) return null
    legs.unshift(e)
    cur = e.from
  }
  return { total, legs }
}

/** Places worth offering in a picker: those you can actually board from or land at. */
export function connectedPlaces(data: TravelFile): TravelPlace[] {
  const used = new Set<number>()
  for (const e of data.edges) {
    used.add(e.from)
    used.add(e.to)
  }
  return data.places.filter((p) => used.has(p.id)).sort((a, b) => a.name.localeCompare(b.name))
}

/** "110 gp" / "gratis" — a fare, in the reader's language. */
export function fareLabel(cost: number, lang: string): string {
  if (cost > 0) return `${cost.toLocaleString(lang.startsWith('es') ? 'es-ES' : 'en-GB')} gp`
  return lang.startsWith('es') ? 'gratis' : 'free'
}
