// --- Mini world changes -------------------------------------------------------
// The "Mini world changes" map layer: the daily dice rolls the server makes at
// start-up — a fury gate in one of ten cities, a nightmare isle on one of three
// coasts, Yasir in one of three ports, the full moon over Grimvale on the 13th.
//
// No live state is claimed anywhere here, and that is deliberate: which one is
// active today is only knowable inside a running world. What the layer shows is
// every place a change CAN land plus the literal line the world says when it
// does — the Town Crier's rhyme, the server broadcast, the portal's refusal.
//
// Data comes from `public/world-changes.json`, generated by
// `node tools/gen-world-changes.mjs` off the OT's own scripts, town-crier NPC
// and world-change .otbm patches. Regenerate after updating the OT tree.
import { useQuery } from '@tanstack/react-query'

/** A rectangle of ground a change swaps in, with the floors it touches. */
export type WcBounds = { x1: number; y1: number; x2: number; y2: number; floors: number[] }

/** One place the change can land. Exactly one of them happens per roll. */
export type WcSpot = {
  /** Stable key (the OT map-patch name), used for React keys and phrase links. */
  key: string
  label: string
  x: number
  y: number
  z: number
  /** Footprint of the map patch, when the change swaps ground in. */
  bounds: WcBounds | null
  /** Crier line naming this spot, for changes that announce the place. */
  phrase: string | null
  /** Full moon: what the 13th puts in the vale, and what it replaces. */
  creatures?: string[]
  instead?: string[]
  /** Day/night NPCs: which half of the Tibian day they stand there. */
  when?: 'day' | 'night'
  npc?: string
}

/** Where the change leads — Fury Hell behind the gate, the isle past the boat. */
export type WcInside = {
  label: string
  x: number
  y: number
  z: number
  bounds: WcBounds
  floors: number[]
  creatures: { name: string; spawns: number }[]
}

/** Something the world literally says. Kept in English — see the panel note. */
export type WcPhrase = {
  from: 'crier' | 'broadcast' | 'portal'
  text: string
  /** Set when the line names one spot (the three nightmare-isle rhymes). */
  spot: string | null
}

export type WorldChange = {
  id: string
  /** daily = rolled every server start; monthly = a date; chance = a % roll. */
  kind: 'daily' | 'monthly' | 'chance' | 'daynight'
  /** Odds of it happening at all, in percent. */
  chance: number
  /** Day of the month it is tied to (the full moon), else null. */
  day: number | null
  spots: WcSpot[]
  inside: WcInside | null
  requirement: { premium: boolean; promoted: boolean; level: number } | null
  phrases: WcPhrase[]
  /** OT files the entry was read from, shown as the layer's provenance. */
  sources: string[]
}

export type WorldChangesFile = { generated: string; changes: WorldChange[] }

/** Baked at build time from the OT scripts — fetch once, keep forever. */
export function useWorldChanges() {
  return useQuery({
    queryKey: ['world-changes'],
    staleTime: Infinity,
    gcTime: Infinity,
    queryFn: async (): Promise<WorldChangesFile> => {
      const res = await fetch('/world-changes.json')
      if (!res.ok) throw new Error('world-changes')
      return res.json()
    },
  })
}

/** Every floor the change touches, spots and destination alike. */
export function wcFloors(c: WorldChange): number[] {
  const floors = new Set<number>()
  for (const s of c.spots) {
    floors.add(s.z)
    for (const f of s.bounds?.floors ?? []) floors.add(f)
  }
  if (c.inside) {
    floors.add(c.inside.z)
    for (const f of c.inside.floors) floors.add(f)
  }
  return [...floors].sort((a, b) => a - b)
}

/**
 * "One of 10 cities, every day" / "The 13th of each month" / "33% of days" —
 * how often, in one phrase. Kept as a translation lookup rather than baked text
 * so both site languages read naturally.
 */
export function wcCadenceKey(c: WorldChange): string {
  if (c.kind === 'monthly') return 'map.wcCadenceMonthly'
  if (c.kind === 'daynight') return 'map.wcCadenceDayNight'
  if (c.chance < 100) return 'map.wcCadenceChance'
  return c.spots.length > 1 ? 'map.wcCadenceDaily' : 'map.wcCadenceDailyOne'
}
